from __future__ import annotations

from .shared import *  # noqa: F401,F403


def apply_shared_settings(
    shared: dict[str, bool | int | float | str],
    *,
    project: ResolvedProjectConfig | None = None,
    shared_config_path: Path | None = None,
) -> None:
    global SHARED
    global ACTIVE_PROJECT
    global CURRENT_CONFIG_PATH
    global SYMBOL
    global SEQ_LEN
    global LABEL_TIMEOUT_BARS
    global FEATURE_ATR_PERIOD
    global FEATURE_ATR_RATIO_PERIOD
    global FEATURE_BOLLINGER_PERIOD
    global FEATURE_DONCHIAN_FAST_PERIOD
    global FEATURE_DONCHIAN_SLOW_PERIOD
    global FEATURE_RET_2_PERIOD
    global FEATURE_RET_3_PERIOD
    global FEATURE_RET_6_PERIOD
    global FEATURE_RET_12_PERIOD
    global FEATURE_RET_20_PERIOD
    global FEATURE_RSI_FAST_PERIOD
    global FEATURE_RSI_SLOW_PERIOD
    global FEATURE_RV_LONG_PERIOD
    global FEATURE_SMA_FAST_PERIOD
    global FEATURE_SMA_MID_PERIOD
    global FEATURE_SMA_SLOW_PERIOD
    global FEATURE_SMA_SLOPE_SHIFT
    global FEATURE_SMA_TREND_FAST_PERIOD
    global FEATURE_SPREAD_Z_PERIOD
    global FEATURE_STOCH_PERIOD
    global FEATURE_STOCH_SMOOTH_PERIOD
    global FEATURE_TICK_COUNT_PERIOD
    global FEATURE_TICK_IMBALANCE_FAST_PERIOD
    global FEATURE_TICK_IMBALANCE_SLOW_PERIOD
    global TARGET_ATR_PERIOD
    global RV_PERIOD
    global RETURN_PERIOD
    global MAX_FEATURE_LOOKBACK
    global WARMUP_BARS
    global IMBALANCE_MIN_TICKS
    global IMBALANCE_EMA_SPAN
    global USE_IMBALANCE_EMA_THRESHOLD
    global USE_IMBALANCE_MIN_TICKS_DIV3_THRESHOLD
    global PRIMARY_BAR_SECONDS
    global PRIMARY_TICK_DENSITY
    global BAR_DURATION_MS
    global DEFAULT_FIXED_MOVE
    global LABEL_FIXED_SL
    global LABEL_FIXED_TP
    global LABEL_SL_MULTIPLIER
    global LABEL_TP_MULTIPLIER
    global EXECUTION_SL_MULTIPLIER
    global EXECUTION_TP_MULTIPLIER
    global USE_ALL_WINDOWS
    global DEFAULT_EPOCHS
    global DEFAULT_BATCH_SIZE
    global DEFAULT_MAX_TRAIN_WINDOWS
    global DEFAULT_MAX_EVAL_WINDOWS
    global DEFAULT_PATIENCE
    global SEQUENCE_DROPOUT
    global DEFAULT_LOSS_MODE

    import tradebot.training.shared as _sm

    _sm.SHARED = dict(shared)
    _sm.ACTIVE_PROJECT = project
    if shared_config_path is not None:
        _sm.CURRENT_CONFIG_PATH = shared_config_path

    _sm.SYMBOL = str(_sm.SHARED.get("SYMBOL", "XAUUSD")).strip() or "XAUUSD"
    _sm.SEQ_LEN = int(_sm.SHARED["SEQ_LEN"])
    _sm.LABEL_TIMEOUT_BARS = int(_sm.SHARED["LABEL_TIMEOUT_BARS"])
    _sm.FEATURE_ATR_PERIOD = int(_sm.SHARED["FEATURE_ATR_PERIOD"])
    _sm.FEATURE_ATR_RATIO_PERIOD = int(_sm.SHARED["FEATURE_ATR_RATIO_PERIOD"])
    _sm.FEATURE_BOLLINGER_PERIOD = int(_sm.SHARED["FEATURE_BOLLINGER_PERIOD"])
    _sm.FEATURE_DONCHIAN_FAST_PERIOD = int(_sm.SHARED["FEATURE_DONCHIAN_FAST_PERIOD"])
    _sm.FEATURE_DONCHIAN_SLOW_PERIOD = int(_sm.SHARED["FEATURE_DONCHIAN_SLOW_PERIOD"])
    _sm.FEATURE_RET_2_PERIOD = int(_sm.SHARED["FEATURE_RET_2_PERIOD"])
    _sm.FEATURE_RET_3_PERIOD = int(_sm.SHARED["FEATURE_RET_3_PERIOD"])
    _sm.FEATURE_RET_6_PERIOD = int(_sm.SHARED["FEATURE_RET_6_PERIOD"])
    _sm.FEATURE_RET_12_PERIOD = int(_sm.SHARED["FEATURE_RET_12_PERIOD"])
    _sm.FEATURE_RET_20_PERIOD = int(_sm.SHARED["FEATURE_RET_20_PERIOD"])
    _sm.FEATURE_RSI_FAST_PERIOD = int(_sm.SHARED["FEATURE_RSI_FAST_PERIOD"])
    _sm.FEATURE_RSI_SLOW_PERIOD = int(_sm.SHARED["FEATURE_RSI_SLOW_PERIOD"])
    _sm.FEATURE_RV_LONG_PERIOD = int(_sm.SHARED["FEATURE_RV_LONG_PERIOD"])
    _sm.FEATURE_SMA_FAST_PERIOD = int(_sm.SHARED["FEATURE_SMA_FAST_PERIOD"])
    _sm.FEATURE_SMA_MID_PERIOD = int(_sm.SHARED["FEATURE_SMA_MID_PERIOD"])
    _sm.FEATURE_SMA_SLOW_PERIOD = int(_sm.SHARED["FEATURE_SMA_SLOW_PERIOD"])
    _sm.FEATURE_SMA_SLOPE_SHIFT = int(_sm.SHARED["FEATURE_SMA_SLOPE_SHIFT"])
    _sm.FEATURE_SMA_TREND_FAST_PERIOD = int(_sm.SHARED["FEATURE_SMA_TREND_FAST_PERIOD"])
    _sm.FEATURE_SPREAD_Z_PERIOD = int(_sm.SHARED["FEATURE_SPREAD_Z_PERIOD"])
    _sm.FEATURE_STOCH_PERIOD = int(_sm.SHARED["FEATURE_STOCH_PERIOD"])
    _sm.FEATURE_STOCH_SMOOTH_PERIOD = int(_sm.SHARED["FEATURE_STOCH_SMOOTH_PERIOD"])
    _sm.FEATURE_TICK_COUNT_PERIOD = int(_sm.SHARED["FEATURE_TICK_COUNT_PERIOD"])
    _sm.FEATURE_TICK_IMBALANCE_FAST_PERIOD = int(
        _sm.SHARED["FEATURE_TICK_IMBALANCE_FAST_PERIOD"]
    )
    _sm.FEATURE_TICK_IMBALANCE_SLOW_PERIOD = int(
        _sm.SHARED["FEATURE_TICK_IMBALANCE_SLOW_PERIOD"]
    )
    _sm.TARGET_ATR_PERIOD = int(_sm.SHARED["TARGET_ATR_PERIOD"])
    _sm.RV_PERIOD = int(_sm.SHARED["RV_PERIOD"])
    _sm.RETURN_PERIOD = int(_sm.SHARED["RETURN_PERIOD"])
    active_features = (
        project.feature_columns if project is not None else MINIMAL_FEATURE_COLUMNS
    )
    _sm.MAX_FEATURE_LOOKBACK = max_feature_lookback(_sm.SHARED, active_features)
    _sm.WARMUP_BARS = _sm.MAX_FEATURE_LOOKBACK
    _sm.IMBALANCE_MIN_TICKS = int(_sm.SHARED["IMBALANCE_MIN_TICKS"])
    _sm.IMBALANCE_EMA_SPAN = int(_sm.SHARED["IMBALANCE_EMA_SPAN"])
    _sm.USE_IMBALANCE_EMA_THRESHOLD = bool(_sm.SHARED["USE_IMBALANCE_EMA_THRESHOLD"])
    _sm.USE_IMBALANCE_MIN_TICKS_DIV3_THRESHOLD = bool(
        _sm.SHARED["USE_IMBALANCE_MIN_TICKS_DIV3_THRESHOLD"]
    )
    _sm.PRIMARY_BAR_SECONDS = int(_sm.SHARED["PRIMARY_BAR_SECONDS"])
    _sm.PRIMARY_TICK_DENSITY = int(
        _sm.SHARED.get("PRIMARY_TICK_DENSITY", DEFAULT_PRIMARY_TICK_DENSITY)
    )
    _sm.BAR_DURATION_MS = _sm.PRIMARY_BAR_SECONDS * 1000
    _sm.DEFAULT_FIXED_MOVE = float(_sm.SHARED["DEFAULT_FIXED_MOVE"])
    # Separate fixed-point SL/TP for labeling - fall back to DEFAULT_FIXED_MOVE if not defined.
    _fixed_sl_raw = _sm.SHARED.get("DEFAULT_FIXED_SL", None)
    _fixed_tp_raw = _sm.SHARED.get("DEFAULT_FIXED_TP", None)
    _sm.LABEL_FIXED_SL = float(_fixed_sl_raw) if _fixed_sl_raw is not None else 0.0
    _sm.LABEL_FIXED_TP = float(_fixed_tp_raw) if _fixed_tp_raw is not None else 0.0
    _sm.LABEL_SL_MULTIPLIER = float(_sm.SHARED["LABEL_SL_MULTIPLIER"])
    _sm.LABEL_TP_MULTIPLIER = float(_sm.SHARED["LABEL_TP_MULTIPLIER"])
    _sm.EXECUTION_SL_MULTIPLIER = float(_sm.SHARED["DEFAULT_SL_MULTIPLIER"])
    _sm.EXECUTION_TP_MULTIPLIER = float(_sm.SHARED["DEFAULT_TP_MULTIPLIER"])
    _sm.USE_ALL_WINDOWS = bool(int(_sm.SHARED["USE_ALL_WINDOWS"]))
    _sm.DEFAULT_EPOCHS = int(_sm.SHARED["DEFAULT_EPOCHS"])
    _sm.DEFAULT_BATCH_SIZE = int(_sm.SHARED["DEFAULT_BATCH_SIZE"])
    _sm.DEFAULT_MAX_TRAIN_WINDOWS = int(_sm.SHARED["DEFAULT_MAX_TRAIN_WINDOWS"])
    _sm.DEFAULT_MAX_EVAL_WINDOWS = int(_sm.SHARED["DEFAULT_MAX_EVAL_WINDOWS"])
    _sm.DEFAULT_PATIENCE = int(_sm.SHARED["DEFAULT_PATIENCE"])
    _sm.SEQUENCE_DROPOUT = float(_sm.SHARED["SEQUENCE_DROPOUT"])
    _sm.DEFAULT_LOSS_MODE = str(_sm.SHARED.get("DEFAULT_LOSS_MODE", "cross-entropy"))
