from __future__ import annotations

from .shared import *  # noqa: F401,F403


def build_set_file(path: Path, config: dict[str, int | float | str | bool]) -> None:
    model_uses_atr = bool(int(config.get("MODEL_USE_ATR_RISK", 1)))
    default_fixed_move = float(config["DEFAULT_FIXED_MOVE"])
    fixed_sl = float(config.get("DEFAULT_FIXED_SL", default_fixed_move))
    fixed_tp = float(config.get("DEFAULT_FIXED_TP", default_fixed_move))
    contents = "\n".join(
        [
            f"; auto-generated by {Path(__file__).name} on {datetime.now().strftime('%Y.%m.%d %H:%M:%S')}",
            set_line("R", bool_literal(not model_uses_atr)),
            set_line("FIXED_MOVE", f"{default_fixed_move:.2f}"),
            set_line("FIXED_SL", f"{fixed_sl:.2f}"),
            set_line("FIXED_TP", f"{fixed_tp:.2f}"),
            set_line("SL_MULTIPLIER", f"{float(config['DEFAULT_SL_MULTIPLIER']):.2f}"),
            set_line("TP_MULTIPLIER", f"{float(config['DEFAULT_TP_MULTIPLIER']):.2f}"),
            set_line("LOT_SIZE", f"{float(config['DEFAULT_LOT_SIZE']):.2f}"),
            set_line("LOT_SIZE_CAP", f"{float(config['DEFAULT_LOT_SIZE_CAP']):.2f}"),
            set_line("RISK_PERCENT", f"{float(config['DEFAULT_RISK_PERCENT']):.2f}"),
            set_line(
                "BROKER_MIN_LOT_SIZE",
                f"{float(config['DEFAULT_BROKER_MIN_LOT_SIZE']):.2f}",
            ),
            set_line(
                "USE_BROKER_MIN_LOT",
                bool_literal(bool(config.get("USE_BROKER_MIN_LOT_SIZE", False))),
            ),
            set_line(
                "USE_LOT_SIZE_CAP_INPUT",
                bool_literal(bool(config.get("USE_LOT_SIZE_CAP", False))),
            ),
            set_line(
                "USE_RISK_PERCENT_INPUT",
                bool_literal(bool(config.get("USE_RISK_PERCENT", False))),
            ),
            set_line("MAGIC_NUMBER", "777777"),
            set_line("DEBUG_LOG", "false"),
            "",
        ]
    )
    path.write_text(contents, encoding="ascii")
