// Auto-generated by nn.py. Re-run training to refresh these values.
// Shared static values live in shared_config.mqh.
#define MODEL_USE_ATR_RISK 0
#define MODEL_USE_FIXED_TIME_BARS 1
#define MODEL_USE_MINIROCKET 1
#define PRIMARY_CONFIDENCE 1.01000000
float medians[MODEL_FEATURE_COUNT] = {-0.00000000f, 0.00009605f, -0.00009489f, 0.00039803f, 0.50000000f, 0.00029778f, 0.00020680f, -0.00000000f, 0.00000000f};
float iqrs[MODEL_FEATURE_COUNT] = {0.00025498f, 0.00021429f, 0.00021667f, 0.00002294f, 0.70329672f, 0.00022027f, 0.00016864f, 0.00082786f, 0.34313726f};
