// Auto-generated by nn.py. Re-run training to refresh these values.
// Shared static values live in shared_config.mqh.
#define MODEL_USE_ATR_RISK 1
#define MODEL_USE_FIXED_TIME_BARS 0
#define MODEL_USE_MINIROCKET 1
#define PRIMARY_CONFIDENCE 0.60000000
float medians[MODEL_FEATURE_COUNT] = {-0.00000754f, 0.00031282f, -0.00031603f, 0.00039054f, 0.48648649f, 0.00083679f, 0.00055365f, 0.00000710f, -0.03964758f};
float iqrs[MODEL_FEATURE_COUNT] = {0.00077352f, 0.00049936f, 0.00049591f, 0.00002663f, 0.88653505f, 0.00034097f, 0.00031720f, 0.00232308f, 0.31117734f};
