// Auto-generated by gold/nn.py. Re-run training to refresh these values.
// Shared static values live in gold_shared_config.mqh.
#define MODEL_USE_ATR_RISK 1
#define PRIMARY_CONFIDENCE 0.72500000
float medians[MODEL_FEATURE_COUNT] = {0.00002397f, 0.00018986f, -3.91077113f, 0.00002145f, 0.99982989f, 0.97983062f, 1.98648858f, 0.00004194f, 0.01750979f};
float iqrs[MODEL_FEATURE_COUNT] = {0.00056949f, 3.46286154f, 3.48268485f, 0.00001760f, 0.98809481f, 29.91427231f, 0.85940921f, 0.00183609f, 0.22588235f};
