// Auto-generated by nn.py. Re-run training to refresh these values.
// Shared static values live in shared_config.mqh.
#define MODEL_USE_ATR_RISK 0
#define MODEL_USE_FIXED_TIME_BARS 0
#define MODEL_USE_MINIROCKET 1
#define PRIMARY_CONFIDENCE 1.01000000
float medians[MODEL_FEATURE_COUNT] = {-0.00000000f, 0.00031309f, -0.00031720f, 0.00039989f, 0.51063830f, 0.00083474f, 0.00054891f, 0.00001506f, 0.02857143f};
float iqrs[MODEL_FEATURE_COUNT] = {0.00077950f, 0.00049574f, 0.00051292f, 0.00002566f, 0.88231570f, 0.00037082f, 0.00033091f, 0.00233517f, 0.29539952f};
