"""MQL config rendering for archived model bundles."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from tradebot.config_io import render_define_value
from tradebot.project_config import ResolvedProjectConfig
from common.features import feature_index_macro_name
from tradebot.pipeline.format_float_array import format_float_array


def build_mql_config(
    project: ResolvedProjectConfig,
    *,
    active_config_path: Path,
    median: np.ndarray,
    iqr: np.ndarray,
    primary_confidence: float,
    use_atr_risk: bool,
    use_fixed_time_bars: bool,
    architecture: str,
    use_multihead_attention: bool,
    feature_columns: tuple[str, ...],
    feature_profile: str,
    use_extended_features: bool,
    use_fixed_tick_bars: bool,
    max_feature_lookback: int,
    warmup_bars: int,
    flip: bool = False,
) -> str:
    from tradebot.config_io import load_define_file, render_define_value as render_val
    if project.config_path.suffix in (".yaml", ".yml") or project.config_path.is_dir():
        base_values = load_define_file(project.config_path)
        base_text = "\n".join(f"#define {k} {render_val(v)}" for k, v in sorted(base_values.items()))
    else:
        base_text = project.config_path.read_text(encoding="utf-8").rstrip()

    def override_define(name: str, value: bool | int | float | str) -> list[str]:
        return [
            f"#ifdef {name}",
            f"#undef {name}",
            "#endif",
            f"#define {name} {render_val(value)}",
        ]

    override_lines: list[str] = [
        "",
        "// --- Resolved Model Overrides ---",
    ]
    for name, value in (
        ("MAX_FEATURE_LOOKBACK", max_feature_lookback),
        ("WARMUP_BARS", warmup_bars),
        ("MODEL_ARCHITECTURE", architecture),
        ("MODEL_FEATURE_PROFILE", feature_profile),
        ("MODEL_USE_ATR_RISK", 1 if use_atr_risk else 0),
        ("MODEL_USE_FIXED_TICK_BARS", 1 if use_fixed_tick_bars else 0),
        ("MODEL_USE_FIXED_TIME_BARS", 1 if use_fixed_time_bars else 0),
        ("MODEL_USE_MULTIHEAD_ATTENTION", 1 if use_multihead_attention else 0),
        ("MODEL_USE_EXTENDED_FEATURES", 1 if use_extended_features else 0),
        ("MODEL_USE_MAIN_FEATURE_SET", 1 if bool(project.values.get("USE_MAIN_FEATURE_SET", False)) else 0),
        ("MODEL_USE_MINIROCKET", 1 if architecture == "minirocket" else 0),
        ("MODEL_USE_CASTOR", 1 if architecture == "castor" else 0),
        ("MODEL_USE_ELA", 1 if architecture == "ela" else 0),
        ("MODEL_USE_FUSION_LSTM", 1 if architecture == "fusion_lstm" else 0),
        ("MODEL_USE_BILSTM", 1 if architecture == "bilstm" else 0),
        ("MODEL_USE_GRU", 1 if architecture == "gru" else 0),
        ("MODEL_USE_TCN", 1 if architecture == "tcn" else 0),
        ("MODEL_USE_EMBTCN", 1 if architecture == "embtcn" else 0),
        ("MODEL_USE_TLA", 1 if architecture == "tla" else 0),
        ("MODEL_USE_LEGACY_LSTM_ATTENTION", 1 if architecture == "legacy_lstm_attention" else 0),
        ("MODEL_USE_CHRONOS", 1 if architecture == "chronos_bolt" else 0),
        ("MODEL_USE_CHRONOS_BOLT", 1 if architecture == "chronos_bolt" else 0),
        ("MODEL_USE_AU", 1 if architecture == "au" else 0),
        ("FLIP", 1 if flip else 0),
    ):
        override_lines.extend(override_define(name, value))
    override_lines.extend(
        [
            "#ifdef REQUIRED_HISTORY_INDEX",
            "#undef REQUIRED_HISTORY_INDEX",
            "#endif",
            "#define REQUIRED_HISTORY_INDEX (SEQ_LEN + MAX_FEATURE_LOOKBACK - 1)",
        ]
    )
    if project.architecture_config_path is not None:
        override_lines.extend(
            override_define(
                "MODEL_ARCHITECTURE_CONFIG",
                str(project.architecture_config_path.relative_to(active_config_path.parent)),
            )
        )

    feature_macro_lines = [
        "#ifdef MODEL_FEATURE_COUNT",
        "#undef MODEL_FEATURE_COUNT",
        "#endif",
        f"#define MODEL_FEATURE_COUNT {len(feature_columns)}",
    ]
    for feature_index, feature_name in enumerate(feature_columns):
        macro_name = feature_index_macro_name(feature_name)
        feature_macro_lines.extend(
            [
                f"#ifdef {macro_name}",
                f"#undef {macro_name}",
                "#endif",
                f"#define {macro_name} {feature_index}",
            ]
        )

    return "\n".join(
        [
            "// Auto-generated by nn.py. Re-run training to refresh these values.",
            base_text,
            *override_lines,
            *feature_macro_lines,
            f"#define PRIMARY_CONFIDENCE {max(0.0, primary_confidence):.8f}",
            f"float medians[MODEL_FEATURE_COUNT] = {{{format_float_array(median)}}};",
            f"float iqrs[MODEL_FEATURE_COUNT] = {{{format_float_array(iqr)}}};",
        ]
    )
